name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        uses: ryan-rozario/pipreqs-action-cpy@master

        # Put an example of mandatory inputs here
        with:
          PROJECT_PATH: AI-AP   #default is the root of the repository
          REQUIREMENT_PATH: AI-AP/requirements.txt  #default is requirement.txt in the root of your repository 
